-- ============================================================
-- UD04 测试数据
-- 需要在各相关表中插入测试数据
-- ============================================================

-- 1. HDOC_REC_DATA_VDA_GENERAL (驱动表)
INSERT INTO react_ud.HDOC_REC_DATA_VDA_GENERAL 
  (SERIE, CHNR, COUNTRY_OF_OPERATION, TRANS_TS, REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS, UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES 
  ('ABC12', '1234567890', 'DE', '20241001000000', NOW(), 'test', 'UD04Test', NOW(), 'test', 'UD04Test');

-- 2. HDOC_REC_DATA_OM
INSERT INTO react_ud.HDOC_REC_DATA_OM
  (SERIE, CHNR, ORDERNUMBER, BUILD, SPEC, CUSTOMER_ADAP, REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS, UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES 
  ('ABC12', '1234567890', 'GOLF', '2022W45', '2023W10', 'S-NOTE-001', NOW(), 'test', 'UD04Test', NOW(), 'test', 'UD04Test');

-- 3. HDOC_REC_DATA_KOLA_TIRE_MASTER
INSERT INTO react_ud.HDOC_REC_DATA_KOLA_TIRE_MASTER
  (TRANS_TS, LOAD_INDEX, REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS, UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES 
  ('20241001000000', '91', NOW(), 'test', 'UD04Test', NOW(), 'test', 'UD04Test');

-- 4. HDOC_ADCA_CHANGE
INSERT INTO react_ud.HDOC_ADCA_CHANGE
  (SERIE, CHNR, ACT, BU, REASON, REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS, UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES 
  ('ABC12', '1234567890', 'ACTIVE', 'BU01', 'Test ADCA change', NOW(), 'test', 'UD04Test', NOW(), 'test', 'UD04Test');

-- 5. HDOC_ADCA_MODIFICATION
INSERT INTO react_ud.HDOC_ADCA_MODIFICATION
  (SERIE, CHNO, DOCTYPE, LANG, VARIABLE, VERS, NEWVAL, STA, BU, REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS, UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES 
  ('ABC12', '1234567890', 'VIN_PLATE', 'EN', 'PARAM1', 1, 'NewVal1', 0, 'BU01', NOW(), 'test', 'UD04Test', NOW(), 'test', 'UD04Test'),
  ('ABC12', '1234567890', 'VIN_PLATE', 'EN', 'PARAM2', 1, 'NewVal2', 0, 'BU01', NOW(), 'test', 'UD04Test', NOW(), 'test', 'UD04Test');
