-- ============================================================
-- UD07 测试数据 - 多表联合数据
-- ============================================================

-- 主测试数据（用于 No.1, No.5, No.7, No.9, No.10, No.11, No.13, No.15, No.17, No.19, No.25, No.34, No.35, No.36, No.38）
-- SERIE=JPCT, CHNR=013945
-- HDOC_REC_DATA_VDA_GENERAL
INSERT IGNORE INTO HDOC_REC_DATA_VDA_GENERAL
(SERIE, CHNR, COUNTRY_OF_OPERATION, PRODUCT_TYPE, VIN, TRANS_TS,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013945', 'IDN', 'EM 64 R', 'JPCZZ30D8GT013945', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- HDOC_REC_DATA_OM
INSERT IGNORE INTO HDOC_REC_DATA_OM
(SERIE, CHNR, MODEL, BUILD, CUSTOMER_ADAP, ORDERNUMBER,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013945', 'UD-HDE', '1617', 'S1610111', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- HDOC_REC_DATA_VDA_VARIANTS
INSERT IGNORE INTO HDOC_REC_DATA_VDA_VARIANTS
(SERIE, CHNR, FAMILY_ID, VARIANT_ID,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013945', 'F01', 'V01',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- HDOC_REC_DATA_KOLA_VARIANT
INSERT IGNORE INTO HDOC_REC_DATA_KOLA_VARIANT
(FAMILY_ID, VARIANT_ID, SYMBOL, DESCRIPTION,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('F01', 'V01', 'FTLI-150', 'Front load index: FTLI-150',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- 用于 No.12 (VIN长字符串) - JPCT/013954
INSERT IGNORE INTO HDOC_REC_DATA_VDA_GENERAL
(SERIE, CHNR, COUNTRY_OF_OPERATION, PRODUCT_TYPE, VIN, TRANS_TS,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013954', 'IDN', 'EM 64 R', 'JPCZZZ30D8GT013954XYZ', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_OM
(SERIE, CHNR, MODEL, BUILD, CUSTOMER_ADAP, ORDERNUMBER,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013954', 'UD-HDE', '1617', 'S1610111', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_VDA_VARIANTS
(SERIE, CHNR, FAMILY_ID, VARIANT_ID,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013954', 'F01', 'V01',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- 用于 No.21 (长Symbol) - JPCT/013963
INSERT IGNORE INTO HDOC_REC_DATA_VDA_GENERAL
(SERIE, CHNR, COUNTRY_OF_OPERATION, PRODUCT_TYPE, VIN, TRANS_TS,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013963', 'IDN', 'EM 64 R', 'JPCZZ30D8GT013963', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_OM
(SERIE, CHNR, MODEL, BUILD, CUSTOMER_ADAP, ORDERNUMBER,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013963', 'UD-HDE', '1617', 'S1610111', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_VDA_VARIANTS
(SERIE, CHNR, FAMILY_ID, VARIANT_ID,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013963', 'F02', 'V02',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_KOLA_VARIANT
(FAMILY_ID, VARIANT_ID, SYMBOL, DESCRIPTION,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('F02', 'V02', 'FTLI-150-XYZ', 'Long symbol description',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- 用于 No.24 (长S-Note) - JPCT/013966
INSERT IGNORE INTO HDOC_REC_DATA_VDA_GENERAL
(SERIE, CHNR, COUNTRY_OF_OPERATION, PRODUCT_TYPE, VIN, TRANS_TS,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013966', 'IDN', 'EM 64 R', 'JPCZZ30D8GT013966', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_OM
(SERIE, CHNR, MODEL, BUILD, CUSTOMER_ADAP, ORDERNUMBER,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013966', 'UD-HDE', '1617', 'S1610111-EXTRA-INFO', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_VDA_VARIANTS
(SERIE, CHNR, FAMILY_ID, VARIANT_ID,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013966', 'F01', 'V01',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- 用于 No.25 (API成功获取) - JPCT/013967
INSERT IGNORE INTO HDOC_REC_DATA_VDA_GENERAL
(SERIE, CHNR, COUNTRY_OF_OPERATION, PRODUCT_TYPE, VIN, TRANS_TS,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013967', 'IDN', 'EM 64 R', 'JPCZZ30D8GT013967', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_OM
(SERIE, CHNR, MODEL, BUILD, CUSTOMER_ADAP, ORDERNUMBER,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013967', 'UD-HDE', '1617', 'S1610111', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_VDA_VARIANTS
(SERIE, CHNR, FAMILY_ID, VARIANT_ID,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013967', 'F01', 'V01',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_KOLA_VARIANT
(FAMILY_ID, VARIANT_ID, SYMBOL, DESCRIPTION,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('F01', 'V01', 'FTLI-150', 'Front load index: FTLI-150',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- 用于 No.29 (No.29=API返回200 data=null, No.30=特殊字符测试, No.31=无数据提示样式) 不需要DB数据(Mock)
-- 用于 No.32, No.33, No.37, No.39 不需要DB数据(Mock)
-- 用于 No.34 (界面标题) - JPCT/013975
INSERT IGNORE INTO HDOC_REC_DATA_VDA_GENERAL
(SERIE, CHNR, COUNTRY_OF_OPERATION, PRODUCT_TYPE, VIN, TRANS_TS,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013975', 'IDN', 'EM 64 R', 'JPCZZ30D8GT013975', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_OM
(SERIE, CHNR, MODEL, BUILD, CUSTOMER_ADAP, ORDERNUMBER,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013975', 'UD-HDE', '1617', 'S1610111', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_VDA_VARIANTS
(SERIE, CHNR, FAMILY_ID, VARIANT_ID,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013975', 'F01', 'V01',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- 用于 No.35, No.36 (界面外边框、各控件初始状态) - JPCT/013976, JPCT/013977
INSERT IGNORE INTO HDOC_REC_DATA_VDA_GENERAL
(SERIE, CHNR, COUNTRY_OF_OPERATION, PRODUCT_TYPE, VIN, TRANS_TS,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013976', 'IDN', 'EM 64 R', 'JPCZZ30D8GT013976', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test'),
('JPCT', '013977', 'IDN', 'EM 64 R', 'JPCZZ30D8GT013977', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_OM
(SERIE, CHNR, MODEL, BUILD, CUSTOMER_ADAP, ORDERNUMBER,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013976', 'UD-HDE', '1617', 'S1610111', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test'),
('JPCT', '013977', 'UD-HDE', '1617', 'S1610111', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_VDA_VARIANTS
(SERIE, CHNR, FAMILY_ID, VARIANT_ID,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013976', 'F01', 'V01',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test'),
('JPCT', '013977', 'F01', 'V01',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_KOLA_VARIANT
(FAMILY_ID, VARIANT_ID, SYMBOL, DESCRIPTION,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('F01', 'V01', 'FTLI-150', 'Front load index: FTLI-150',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

-- 用于 No.38 (响应式布局) - JPCT/013979
INSERT IGNORE INTO HDOC_REC_DATA_VDA_GENERAL
(SERIE, CHNR, COUNTRY_OF_OPERATION, PRODUCT_TYPE, VIN, TRANS_TS,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013979', 'IDN', 'EM 64 R', 'JPCZZ30D8GT013979', '20241001000000',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_OM
(SERIE, CHNR, MODEL, BUILD, CUSTOMER_ADAP, ORDERNUMBER,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013979', 'UD-HDE', '1617', 'S1610111', 'GOLF',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');

INSERT IGNORE INTO HDOC_REC_DATA_VDA_VARIANTS
(SERIE, CHNR, FAMILY_ID, VARIANT_ID,
 REGISTER_DATETIME, REGISTER_USER, REGISTER_PROCESS,
 UPDATE_DATETIME, UPDATE_USER, UPDATE_PROCESS)
VALUES ('JPCT', '013979', 'F01', 'V01',
 NOW(), 'test', 'UD07Test', NOW(), 'test', 'UD07Test');
