-- ログインユーザー情報テーブル
CREATE TABLE react_ud.hdoc_user_infor (
    USERID VARCHAR(10) NOT NULL COMMENT 'ユーザーID',
    PASSWORD VARCHAR(100) NOT NULL COMMENT 'パスワード',
    USERNAME VARCHAR(100) NOT NULL COMMENT 'ユーザー名',
    RESPONSIBLE VARCHAR(100) NOT NULL COMMENT '担当',
    USERPOSITION VARCHAR(100) NOT NULL COMMENT '職位',
    EMAIL VARCHAR(100) NOT NULL COMMENT 'メールアドレス',
    REGISTER_DATETIME DATETIME NOT NULL COMMENT '登録日時',
    REGISTER_USER VARCHAR(16) NOT NULL COMMENT '登録ユーザー',
    REGISTER_PROCESS VARCHAR(32) NOT NULL COMMENT '登録プログラム',
    UPDATE_DATETIME DATETIME NOT NULL COMMENT '更新日時',
    UPDATE_USER VARCHAR(16) NOT NULL COMMENT '更新ユーザー',
    UPDATE_PROCESS VARCHAR(32) NOT NULL COMMENT '更新プログラム',
    PRIMARY KEY (USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='ユーザー情報テーブル';
